---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-deployment
#  namespace: micro
  labels:
    app: micro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
      imagePullSecrets:
        - name: azure-acr-secret
      containers:
        - name: micro
          image: mtarekacr1234.azurecr.io/micro:{{VERSION_TO_BE_REPLACED}}
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: micro-service
#  namespace: micro
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: micro
