---
trigger: ['*']
pool:
  vmImage: ubuntu-latest
variables:
  - template: variables.yml
steps:
  - checkout: self
    clean: true
  - template: templates/build.yml
    parameters:
      registryConfigName: ${{ variables.registryConfigName }}
      repoName: ${{ variables.repoName }}
      dockerfile: ${{ variables.dockerfile }}
  - template: templates/deploy.yml
    parameters:
      kubernetesServiceConnection: ${{ variables.kubernetesServiceConnection }}
      namespace: ${{ variables.namespace }}
      containerReg: ${{ variables.containerReg }}
      imageRepo: ${{ variables.imageRepo }}
      imagePullSecret: ${{ variables.imagePullSecret }}
