---
parameters:
  - name: registryConfigName
    default: mtarekacr1234
  - name: repoName
    default: micro
  - name: dockerfile
    default: '**/Dockerfile'
steps:
  - task: Docker@2
    displayName: Docker Build
    inputs:
      containerRegistry: ${{ parameters.registryConfigName }}
      repository: ${{ parameters.repoName }}
      command: buildAndPush
      Dockerfile: ${{ parameters.dockerfile }}
      tags: $(VERSION)
